### ISSUE TITLE
unresolved externals

### ISSUE THREAD

**Issue by gaymer134** [zorftw/gasper-cpp#2]
building in release x86.
java jdk included

getting a bunch of unresolved externals from imgui:

https://gyazo.com/0f8bfdabfba602474566a81d8b5c4c75

any idea how to fix? ty.

**Comment by ooodummy** [comment]
actually include the files and add opengl32.lib in the linker.

**Comment by gaymer134** [comment]
cheers forgot about that lib :/

**Comment by gaymer134** [comment]
okay its building fine - everything included in project. java jdk included, everything fine compiler wise but when injecting using process hacker nothing happens?

**Comment by ooodummy** [comment]
I legit just responded to one of these, VK_UP to toggle menu. VK_HOME to uninject.

**Comment by gaymer134** [comment]
ye i found that in the src but i press it and nothing happens xD

**Comment by ooodummy** [comment]
maybe num lock is on or you have the mc window minimized so much that the default window position is not visible

**Comment by gaymer134** [comment]
ty for your response - i checked and nope with MC is not minimized and numlock isnt on :/

**Comment by ooodummy** [comment]
contact me on discord your probs doing smthing wrong, no worries.

**Comment by gaymer134** [comment]
sent request - ty very much.

**Comment by ooodummy** [comment]
you can close this issue now

**Comment by zorftw** [comment]
@ooodummy Thanks for helping him out.
Closed.
