### ISSUE TITLE
Says injected but nothing happens

### ISSUE THREAD

**Issue by SwiftSkid** [zorftw/gasper-cpp#3]
Whenever I inject I get a dialog box that says "[dbg] gasper   Injected.", but i don't get any menu. I've pressed every single key on my keyboard and yet nothing. Tried using different injection methods in extreme inject and still nothing. Using 1.7.10-Forge10.13.4.1614-1.7.10 forge with no mods.

**Comment by ooodummy** [comment]
menu key by default is VK_HOME you would see that if you spent a second looking instead of opening a issue.

**Comment by SwiftSkid** [comment]
I pressed that key before, tried it again and still nothing. I saw that in the code, and it has a note "/// "Self-destruct" button" anyways

**Comment by SwiftSkid** [comment]
Thank you. I looked through the code and couldn't find the menu key, could only find the self destruct key. I just didn't look through all of it
