### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by SwiftSkid** [zorftw/gasper-cpp#4]
When I inject, i crash after a couple seconds, maybe you didn't upload the crash fix to github correctly. I tried debugging (don't know if I did it right) and each time I get the error "Unhandled exception at 0x000000006DD52BA2 (jvm.dll) in javaw.exe: 0xC0000005: Access violation reading location 0x0000000000000000."

**Comment by BD9a** [comment]
Same. After allocating console game crashing. Version 1.7.10 / 1.8.9 (Forge). Without forge I got error with "wrapper 0x0"

**Comment by Plowdzn** [comment]
reach doesnt works, it is ever 3.0

**Comment by zorftw** [comment]
I have zero clue where or what caused this error. Debug for yourself.
